[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
hyper = { version = "1.0", features = ["server", "http1"] }
http-body-util = "0.1"
regex = "1.11.1"
hyper-tls = "0.6.0"
hyper-util = "0.1.11"
bytes = "1.10.1"
